### ISSUE TITLE
Login error 403

### ISSUE THREAD

**Issue by syeihansyah23** [im-hanzou/kardpay-autoref#1]
Login error: 403 Client Error: Forbidden for url: https://api.kardpay.app/waitinglist/users/user/login

**Comment by syeihansyah23** [comment]
![image_2024-12-30_084133774](https://github.com/user-attachments/assets/d21567f2-4395-4e02-9f11-e6cbad0f663d)

**Comment by im-hanzou** [comment]
use proxies or no?

**Comment by syeihansyah23** [comment]
yes i use 50 proxies

**Comment by syeihansyah23** [comment]
solved after change to proxyscrape. Thankyou

**Comment by im-hanzou** [comment]
please use rotating proxies

**Comment by im-hanzou** [comment]
nice, good to hear

**Comment by im-hanzou** [comment]
The script has been updated, Please redownload the script or ``git pull``
