### ISSUE TITLE
502 Server Error

### ISSUE THREAD

**Issue by anakdajjalyalo** [im-hanzou/kardpay-autoref#12]
Did paged has down? I've been trying many times open Kardpay Apps doesn't loaded anything.

**Comment by Russszz** [comment]
the apps is sucks to open right now

**Comment by im-hanzou** [comment]
kardpay api down

**Comment by ilcham0202** [comment]
<img width="732" alt="Screenshot 2024-12-31 at 21 39 30" src="https://github.com/user-attachments/assets/5799b85a-3f06-4c44-9d22-7b6745d27e37" />

**Comment by im-hanzou** [comment]
[ PROGRAM ENDED ]
