### ISSUE TITLE
Login Error Without Proxies

### ISSUE THREAD

**Issue by alphastockid0** [im-hanzou/kardpay-autoref#4]
Login error: HTTPSConnectionPool(host='api.kardpay.app', port=443): Read timed out. (read timeout=60)

![Uploading Screenshot_20241230-144718_Termux.jpg…]()

**Comment by im-hanzou** [comment]
api down right now, kardpay change their firebase apikey

**Comment by im-hanzou** [comment]
The script has been updated, Please redownload the script or ``git pull``
