### ISSUE TITLE
android client blocked

### ISSUE THREAD

**Issue by ene80** [im-hanzou/kardpay-autoref#7]
After some successful referal start giving this erros:

Register failed: {'error': {'code': 403, 'message': 'Requests from this Android client application <empty> are blocked.', 'errors': [{'message': 'Requests from this Android client application <empty> are blocked.', 'domain': 'global', 'reason': 'forbidden'}], 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_ANDROID_APP_BLOCKED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/469396184392', 'service': 'identitytoolkit.googleapis.com', 'androidPackage': '<empty>'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'Requests from this Android client application <empty> are blocked.'}]}}

**Comment by im-hanzou** [comment]
api down right now, kardpay change their firebase apikey

**Comment by im-hanzou** [comment]
The script has been updated, Please redownload the script or ``git pull``
