### ISSUE TITLE
Register failed 

### ISSUE THREAD

**Issue by Skbindas** [im-hanzou/kardpay-autoref#9]
Register failed: {'error': {'code': 403, 'message': 'Requests from this Android client application <empty> are blocked.', 'errors': [{'message': 'Requests from this Android client application <empty> are blocked.', 'domain': 'global', 'reason': 'forbidden'}], 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_ANDROID_APP_BLOCKED', 'domain': 'googleapis.com', 'metadata': {'service': 'identitytoolkit.googleapis.com', 'androidPackage': '<empty>', 'consumer': 'projects/469396184392'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'Requests from this Android client application <empty> are blocked.'}]}}

**Comment by im-hanzou** [comment]
api down right now, kardpay change their firebase apikey

**Comment by Skbindas** [comment]
Create UXUY Telegram Bot Refer Script project link.  Check this sir 

https://t.me/UXUYbot/app?startapp=A_1149344707_inviteEarn

**Comment by im-hanzou** [comment]
The script has been updated, Please redownload the script or ``git pull``

**Comment by im-hanzou** [comment]
> Create UXUY Telegram Bot Refer Script project link. Check this sir
> 
> https://t.me/UXUYbot/app?startapp=A_1149344707_inviteEarn

sorry im not playing telegram miniapps
